config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root to: "friends#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, :only => [:show]

  resources :friends, only: [:show, :index, :new, :create] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :edit, :update] do
    get :finished, on: :member
    patch :finished, on: :member
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :friend
  AUTHORIZED_STATUS = ["pending", "validated", "declined", "finished"]

  validates :status, inclusion: { in: AUTHORIZED_STATUS }
end

app/models/friend.rb
class Friend < ApplicationRecord
  has_many :bookings
  has_many :reviews, through: :bookings
  belongs_to :user
  has_one_attached :photo
  AUTHORIZED_GENRE = ["Homme", "Femme"]

  validates :name, presence: true
  validates :date_of_birth, presence: true
  validates :genre, presence: true, inclusion: { in: AUTHORIZED_GENRE }
  validates :address, presence: true
  validates :description, presence: true
  validates :photo, presence: true
  validates :price, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  belongs_to :user
  AUTHORIZED_RATINGS = (0..5)

  validates :review_content, presence: true
  validates :review_rating, inclusion: { in: AUTHORIZED_RATINGS }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :friends
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.where(user_id: current_user.id)
    @requests = Booking.joins(friend: :user).where(users: { id: current_user.id }, friends: { user_id: current_user.id })
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new()
    @booking.user = current_user
    @booking.friend = Friend.find(params[:friend_id])
    @booking.status = "pending"
    @booking.start_date = params[:start_date]
    @booking.end_date = params[:end_date]
    if @booking.save
      redirect_to friend_path(@booking.friend), notice: "Votre réservation est en attente de confirmation !"
    else
      redirect_to friend_path(@booking.friend), notice: "Votre réservation a échouée"
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    raise
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      @booking.status = "pending"
      redirect_to bookings_path, notice: "Your booking was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def finished
    @booking = Booking.find(params[:id])
    @booking.status = "finished"
    redirect_to bookings_path, notice: "Votre réservation est terminée !"
  end

  private

  def booking_params
    params.require(:booking).permit(:status, :start_date, :end_date, :total_price)
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :new, :create]

  def index
    if params[:query].present?
      @friends = Friend.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @friends = Friend.all
    end
  end

  def show
    @friend = Friend.find(params[:id])
    @booking = Booking.new
  end

  def new
    @friend = Friend.new
  end

  def create
    @friend = Friend.new(friend_params)
    @friend.user = current_user
    if @friend.save!
      redirect_to friends_path, notice: "Votre ami a été ajouté à l'application RYF ! !"
    else
      render :new, notice: "L'ajout de votre ami à RYF a échoué"
      # render :new, status: :unprocessable_entity
    end
  end

  def friend_params
    params.require(:friend).permit(:name, :date_of_birth, :price, :genre, :address, :photo, :description, :activity_barbecue, :activity_birthday,
      :activity_bowling, :activity_camping, :activity_concert, :activity_diner, :activity_hike, :activity_karaoke, :activity_movie,
      :activity_paintball, :activity_picnic, :activity_sam, :activity_shopping, :activity_sport, :activity_wedding, :default_arrogant,
      :default_cheap, :default_complotist, :default_disorganized, :default_impatient, :quality_brave, :quality_funny, :quality_good_looking,
      :quality_honest, :quality_reliable)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    # @friend = Friend.find(params[:friend_id])
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @review  = Review.new(review_params)
    @review.booking = @booking
    @review.user = current_user
    if @review.save
      redirect_to bookings_path, notice: "Votre avis a été pris en compte"
    else
      render :new, status: :unprocessable_entity, notice: "Impossible d'enregistrer votre avis"
    end
  end

  private

  def review_params
    params.require(:review).permit(:review_content, :review_rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @bookings = Booking.where(user_id: current_user.id)
    @friends = @user.friends
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<h1>Update your booking </h1>

<%= simple_form_for ([@user, @booking]) do |f| %>
<%= f.input :start_date %>
<%= f.input :end_date %>
<%= f.submit %>
<% end %>

app/views/bookings/index.html.erb
<div class="wrapper-bookings">
  <h1 class="booking-title">Vos réservations </h1>
  <% if @bookings == [] %>
    <div class="p">
      <p>Vous n'avez pas encore fait de réservation !
      <%= link_to "Trouvez maintenant des amis parfaits pour vous", friends_path %></p>
    </div>
  <% end %>
  <div class="booking-grid-resa" id="card">
    <% @bookings.each do |booking|%>
    <%= render "shared/booking_card", booking: booking %>
    <%end%>
  </div>
  <h1 class="booking-title">Vos demandes de réservation</h1>
  <% if @requests != [] %>
    <div class="booking-grid-resa">
      <% @requests.each do |request|%>
      <%= render "shared/request_card", request: request %>
      <%end%>
    </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<h1>Create a new booking </h1>

app/views/friends/index.html.erb
<div class="card-category mb-4" id="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://img.freepik.com/photos-gratuite/jeunes-amis-au-sommet-montagne-profitant-vue-fascinante_181624-30260.jpg?w=2000&t=st=1679419524~exp=1679420124~hmac=ea194c3304a747df6b352ae4d1c34fa4f526ee459cf3331321a29009231a38fb)">
  <div class="wrapper-banner">
    <div class="title">
      <h1>Un nouvel ami t'attend</h1>
      <p><em>“Qui trouve un ami, trouve un trésor”</em></p>
    </div>
  </div>
</div>
<div id="wrapper-friends">
  <div class="grid-friends">
      <% colors = ['#3A86FF', '#FB5607', '#2EC4B6', '#8338EC', '#FD1015', '#FFC65A', '#E67E22', '#1EDD88'] %>
    <% @friends.each do |friend| %>
      <% friend_color = colors.sample %>
      <% if colors.any? %>
        <% colors.delete(friend_color) %>
      <% else %>
        <% colors = ['#3A86FF', '#FB5607', '#2EC4B6', '#8338EC', '#FD1015', '#FFC65A', '#E67E22', '#1EDD88'] %>
        <% friend_color = colors.sample %>
      <% end %>
      <%= render "shared/friend_card", friend: friend, friend_color: friend_color %>
    <% end %>
  </div>
</div>
<script>
    const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]');
    const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl));
    // const exampleEl = document.getElementById('example');
    // const tooltip = new bootstrap.Tooltip(exampleEl, options);

    //Tried this; didn't work:
    // $(function () {
    //     $('[data-toggle="tooltip"]').tooltip()
    // })

</script>

app/views/friends/new.html.erb
  <div class="en-tete-new"><h1><strong> Renseignez les informations de votre friend </strong></h1>
  <h2>Il vous en sera éternellement reconnaissant !</h2>
  </div>
<div class= "new-friend-container", data-controller="try">
  <%= simple_form_for @friend, html: { data: { action:"submit->try#tada"}} do |f| %>
    <%= f.input :name,wrapper_html: { class: 'form-group' }, label:"Prénom" %>
    <%= f.input :date_of_birth, required: true, label: "Date de naissance", as: :string, input_html: { data: { controller: "datepicker", locale: "fr"} }%>
    <%= f.input :price, input_html: { min: 0 }, label: "Prix journalier" %>
    <%= f.input :genre, collection: ["Homme", "Femme"] %>
    <%= f.input :address, label: "Adresse de votre friend" %>

    <p class="titre-p-newfriend"><strong>Quelles sont ses activités préférées ?</strong></p>
    <%= f.input :activity_wedding, as: :boolean, label:"Participation aux mariages" %>
    <%= f.input :activity_sam, as: :boolean, label:"Être Sam pour vos soirées" %>
    <%= f.input :activity_diner, as: :boolean, label:"Participation aux dîners" %>
    <%= f.input :activity_birthday, as: :boolean, label:"Participation aux anniversaires" %>
    <%= f.input :activity_bowling, as: :boolean, label:"Participation aux parties de bowling" %>
    <%= f.input :activity_hike, as: :boolean, label:"Participation aux randonnées" %>
    <%= f.input :activity_movie, as: :boolean, label:"Visionnage de films" %>
    <%= f.input :activity_picnic, as: :boolean, label:"Participation aux pinics" %>
    <%= f.input :activity_concert, as: :boolean, label:"Participation aux concerts" %>
    <%= f.input :activity_karaoke, as: :boolean, label:"Participation aux karaokés" %>
    <%= f.input :activity_shopping, as: :boolean, label:"Accompagnement au shopping" %>
    <%= f.input :activity_sport, as: :boolean, label:"Participation aux activités sportives" %>
    <%= f.input :activity_barbecue, as: :boolean, label:"Participation aux barbecues (cuisson non-inclue)" %>
    <%= f.input :activity_camping, as: :boolean, label:"Accompagnement sorties camping (frais annexes : montage et dépliage de tente)" %>
    <%= f.input :activity_paintball, as: :boolean, label:"Participation aux parties de paintball" %>

    <p class="titre-p-newfriend"><strong>Quels sont ses petits défauts ?<br></strong></p>
    <%= f.input :default_complotist, as: :boolean, label:"Complotiste?" %>
    <%= f.input :default_impatient, as: :boolean, label:"Impatient.e?" %>
    <%= f.input :default_disorganized, as: :boolean, label:"désorganisé.e?"%>
    <%= f.input :default_cheap, as: :boolean, label:"Radin.e?" %>
    <%= f.input :default_arrogant, as: :boolean, label:"arrogant.e?" %>

    <p class="titre-p-newfriend"><strong>Quelles sont ses qualités ?<br></strong></p>
    <%= f.input :quality_funny, as: :boolean, label:"Amusant.e?" %>
    <%= f.input :quality_reliable, as: :boolean, label:"Fiable?" %>
    <%= f.input :quality_honest, as: :boolean, label:"Honnête?" %>
    <%= f.input :quality_good_looking, as: :boolean, label:"Un physique agréable?" %>
    <%= f.input :quality_brave, as: :boolean, label:"Courageux.se?" %>

    <p class="titre-p-newfriend"><strong>Et c'est pas fini...<br></strong></p>
    <%= f.input :user_id, as: :hidden, value: current_user.id %>
    <%= f.input :photo, as: :file, label:"À quoi votre friend ressemble-t-il/elle?"  %>
    <%= f.input :description, label:"Présentez votre friend ! Soyez sincère, ses défauts peuvent également être ses qualités !" %>
    <%= f.button :submit, class: "button-primary-large", label:"ajoute ton friend <br> (il/elle te remerciera)"  %>
    </div>
  <% end %>
</div>

app/views/friends/show.html.erb
<section class="container-show">
  <section class="card-user-left">
    <div class="img-profile">
      <%= cl_image_tag  @friend.photo.key %>
      <h1><strong> Rencontre <%= @friend.name.capitalize %></strong></h1>
      <p> <%= @friend.description %> </p>
    </div>
  </section>

<section class="card-informations">
    <div class="friend-activities">
      <h3><strong> Disponible pour </strong></h3>
      <div class="grid-activities" >
        <% if @friend.activity_wedding? %>
          <i class="fa-solid fa-ring" style="color: #754285;"></i>
        <% else %>
          <i class="fa-solid fa-ring" style="color: rgba(0, 0, 0, 0.1);"></i>
        <% end %>

        <% if @friend.activity_sam? %>
          <i class="fa-solid fa-car" style="color: #754285;"></i>
        <% else %>
          <i class="fa-solid fa-car" style="color: rgba(0, 0, 0, 0.1);"></i>
        <% end %>

        <% if @friend.activity_diner? %>
          <i class="fa-solid fa-utensils" style="color: #754285;"></i>
        <% else %>
          <i class="fa-solid fa-utensils" style="color: rgba(0, 0, 0, 0.1);"></i>
        <% end %>

        <% if @friend.activity_birthday? %>
          <i class="fa-solid fa-cake-candles" style="color: #754285;"></i>
        <% else %>
          <i class="fa-solid fa-cake-candles" style="color: rgba(0, 0, 0, 0.1);"></i>
        <% end %>

        <% if @friend.activity_bowling? %>
          <i class="fa-solid fa-bowling-ball" style="color: #754285;"></i>
        <% else %>
          <i class="fa-solid fa-bowling-ball" style="color: rgba(0, 0, 0, 0.1);"></i>
        <% end %>

        <% if @friend.activity_hike? %>
          <i class="fa-solid fa-person-hiking" style="color: #754285;"></i>
        <% else %>
          <i class="fa-solid fa-person-hiking" style="color: rgba(0, 0, 0, 0.1);"></i>
        <% end %>

        <% if @friend.activity_movie? %>
          <i class="fa-solid fa-film" style="color: #754285;"></i>
        <% else %>
          <i class="fa-solid fa-film" style="color: rgba(0, 0, 0, 0.1);"></i>
        <% end %>

        <% if @friend.activity_picnic? %>
          <i class="fa-solid fa-campground" style="color: #754285;"></i>
        <% else %>
          <i class="fa-solid fa-campground" style="color: rgba(0, 0, 0, 0.1);"></i>
        <% end %>

        <% if @friend.activity_concert? %>
          <i class="fa-solid fa-guitar" style="color: #754285;"></i>
        <% else %>
          <i class="fa-solid fa-guitar" style="color: rgba(0, 0, 0, 0.1);"></i>
        <% end %>

        <% if @friend.activity_karaoke? %>
          <i class="fa-solid fa-music" style="color: #754285;"></i>
        <% else %>
          <i class="fa-solid fa-music" style="color: rgba(0, 0, 0, 0.1);"></i>
        <% end %>

        <% if @friend.activity_shopping? %>
          <i class="fa-solid fa-bag-shopping" style="color: #754285;"></i>
        <% else %>
          <i class="fa-solid fa-bag-shopping" style="color: rgba(0, 0, 0, 0.1);"></i>
        <% end %>

        <% if @friend.activity_sport? %>
          <i class="fa-solid fa-dumbbell" style="color: #754285;"></i>
        <% else %>
          <i class="fa-solid fa-dumbbell" style="color: rgba(0, 0, 0, 0.1);"></i>
        <% end %>

        <% if @friend.activity_barbecue? %>
          <i class="fa-solid fa-fire-burner" style="color: #754285;"></i>
        <% else %>
          <i class="fa-solid fa-fire-burner" style="color: rgba(0, 0, 0, 0.1);"></i>
        <% end %>

        <% if @friend.activity_camping? %>
          <i class="fa-solid fa-caravan" style="color: #754285;"></i>
        <% else %>
          <i class="fa-solid fa-caravan" style="color: rgba(0, 0, 0, 0.1);"></i>
        <% end %>

        <% if @friend.activity_paintball? %>
          <i class="fa-solid fa-gun" style="color: #754285;"></i>
        <% else %>
          <i class="fa-solid fa-gun" style="color: rgba(0, 0, 0, 0.1);"></i>
        <% end %>
      </div>
    </div>
    <div class="friend-qualities">
      <h3> <strong><%= @friend.name.capitalize %> est très </strong></h3>
      <div>
        <% if @friend.genre == "Homme" %>
          <% if @friend.quality_funny? %>
            <p>Drôle</p>
          <% end %>

          <% if @friend.quality_reliable? %>
            <p>Fiable</p>
          <% end %>

          <% if @friend.quality_honest? %>
            <p>Honnête</p>
          <% end %>

          <% if @friend.quality_good_looking? %>
            <p>Stylé</p>
          <% end %>

          <% if @friend.quality_brave? %>
            <p>Courageux</p>
          <% end %>
        <% else %>
          <% if @friend.quality_funny? %>
              <p>Drôle</p>
            <% end %>

            <% if @friend.quality_reliable? %>
              <p>Fiable</p>
            <% end %>

            <% if @friend.quality_honest? %>
              <p>Honnête</p>
            <% end %>

            <% if @friend.quality_good_looking? %>
              <p>Stylée</p>
            <% end %>

            <% if @friend.quality_brave? %>
              <p>Courageuse</p>
            <% end %>
        <% end %>
      </div>
    </div>
    <div class="friend-defaults">
      <h3><strong> Mais aussi très </strong></h3>
      <div>
        <% if @friend.genre == "Homme" %>
          <% if @friend.default_complotist? %>
            <p class="default" >Complotiste</p>
          <% end %>

          <% if @friend.default_impatient? %>
            <p class="default">Impatient</p>
          <% end %>

          <% if @friend.default_disorganized? %>
            <p class="default">Bordelique</p>
          <% end %>

          <% if @friend.default_cheap? %>
            <p class="default">Radin</p>
          <% end %>

          <% if @friend.default_arrogant? %>
            <p class="default">Arrogant</p>
          <% end %>
        <% else %>
          <% if @friend.default_complotist? %>
            <p class="default" >Complotiste</p>
          <% end %>

          <% if @friend.default_impatient? %>
            <p class="default">Impatiente</p>
          <% end %>

          <% if @friend.default_disorganized? %>
            <p class="default">Bordelique</p>
          <% end %>

          <% if @friend.default_cheap? %>
            <p class="default">Radine</p>
          <% end %>

          <% if @friend.default_arrogant? %>
            <p class="default">Arrogante</p>
          <% end %>
        <% end %>
      </div>
    </div>
</section>
<section class="card-booking-right" data-controller="show-price" data-show-price-friendid-value="<%=@friend.id%>" data-show-price-prixTotal-value="<%=@friend.price%>">
      <div class="price-user">
        <p><strong><%= @friend.price %>€</strong> par jour</p>
        <div class="reviews">
          <p>4.5</p>&nbsp;
          <p>Avis</p>
        </div>
      </div>
      <div class="formulaire">
        <%= simple_form_for [@friend, Booking.new], html: { data: { action:"submit->show-price#reserve"}} do |f| %>
          <%= f.input :start_date, required: true, label: "Début", as: :string, input_html: { data: { controller: "datepicker", action:"change->show-price#calculate", show_price_target:"dateDebut", locale: "fr"} }%>
          <%= f.input :end_date, required: true, label: "Fin", as: :string, input_html: { data: { controller: "datepicker", action:"change->show-price#calculate", show_price_target:"dateFin" } } %>
          <%= f.button :submit, "Réserver", class: "button-primary-large", data: {turbo_confirm: "Are you sure?"} %>
          </div>
        <% end %>
        <div class="price-element">
        <div class="label-price">
          <p>Total jours :</p>
          <p id="resultjours"> </p>
        </div>
        <div class="label-price">
          <p>Nettoyage :</p>
          <p>20€</p>
        </div>
        <div class="label-price">
          <p>Remise Défauts :</p>
          <p id="default-numb"></p>
          <p id="remise"></p>
        </div>
      </div>
        <div class="label-price">
          <p> <strong> Prix total :</strong> </p>
          <p id="resultprix"></p>
        </div>
      </div>
  </section>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RYFRentyourfriends</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <%= render "shared/navbar" %>
        <%= yield %>
    <footer>
      <p>© Powered By Frometon</p>
    </footer>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_booking_card.html.erb
<div class="card-booking-resa">
  <div class="card-top-resa">
    <%= image_tag  booking.friend.picture %>
    <% if booking.status == "validated" %>
      <h3><%= booking.friend.name.capitalize %> a hâte de vous voir 😉</h3>
    <% elsif booking.status == "pending" %>
      <h3><%= booking.friend.name.capitalize %> vous attend !😀</h3>
    <% elsif booking.status == "declined" %>
      <h3>Vous ne verrez pas <%= booking.friend.name.capitalize %> 🫣</h3>
    <% else %>
      <h3><%= booking.friend.name.capitalize %> vous remercie 😘</h3>
    <% end %>
  </div>
  <div class="statut-layout">
      <% if booking.status == "validated" %>
        <p class="validated">Statut : Validée</p>
      <% elsif booking.status == "pending" %>
        <p class="pending">Statut : En attente</p>
      <% elsif booking.status == "declined" %>
        <p class="declined">Statut : Refusée</p>
      <% else %>
        <p class="done">Statut : Terminée</p>
      <% end %>
  </div>
  <div class="card-middle-resa">
    <h4>Votre activité est prévue</h4>
    <% if booking.start_date == booking.end_date %>
      <p>Le <%= booking.start_date %></p>
    <% else %>
      <p>Du <strong><%= booking.start_date %></strong> au <strong><%= booking.end_date %></strong></p>
    <% end %>
  </div>
  <div class="card-bottom-resa">
    <p>Contact de <%= booking.user.first_name %></p>
    <div class="icons">
      <i class="fa-solid fa-envelope"></i>
      <i class="fa-solid fa-phone"></i>
      <i class="fa-brands fa-linkedin"></i>
      <i class="fa-brands fa-facebook"></i>
    </div>
  </div>
  <%# <%= booking.total_price %>
  <% if booking.status == "finished" %>
    <%= link_to "Notez votre expérience !", new_booking_review_path(booking), class: "button-primary" %>
  <% else %>
    <%= link_to "Modifier votre réservation", edit_booking_path(booking), class: "button-secondary" %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<%# coder la navbar %>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to friends_path, class: "navbar-brand" do %>
      <%= image_tag "RYF.png" %>
    <% end %>

    <div data-controller="navbar">
      <%= form_with url: friends_path, method: :get, id: "form-search" do %>
        <%= text_field_tag :query, params[:query], id: "input-search", placeholder: "Trouvez votre ami", data: { navbar_target: "value" }%>
        <button id="navbar-btn" type="submit" data-action="submit->navbar#connect"><i class="fa fa-search"></i></button>
      <% end %>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "https://pbs.twimg.com/media/CHGbzGeWcAAHthn.jpg:large", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Mon compte", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Mes réservations", bookings_path, class: "dropdown-item" %>
              <%= link_to "Ajouter un ami", new_friend_path, class: "dropdown-item" %>
              <%= link_to "Deconnexion", destroy_user_session_path , class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item"-->
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li-->
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_request_card.html.erb
<div class="card-booking-resa">
  <h5>Demande de réservation pour</h5>
  <div class="card-double-img">
    <div class="left">
      <%= image_tag  request.friend.picture %>
      <%= request.friend.name.capitalize %>
    </div>
    <%# insérer la flêche duo %>
    <i class="fa-solid fa-arrow-right-arrow-left"></i>
    <div class="right">
      <span></span>
      <%= request.user.first_name %>
    </div>
  </div>
  <div class="statut-layout">
      <p>Statut :
        <%= request.status%>
      </p>
    </div>
  <div class="card-middle-resa">
    <h4>Votre activité est prévue</h4>
    <% if request.start_date == request.end_date %>
      <p>Le <%= request.start_date %></p>
    <% else %>
      <p>Du <strong><%= request.start_date %></strong> au <strong><%= request.end_date %></strong></p>
    <% end %>
  </div>
  <div class="button-request">
    <%= link_to "Accepter", bookings_path, class: "button-accept" %>
    <%= link_to "Refuser", bookings_path, class: "button-refus"%>
    <%= link_to "Terminer", finished_booking_path(request.id), method: :update, class:"button-done" %>
  </div>
</div>